name: ci-cd pipeline
on: workflow_dispatch
jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps: 
      - name: send notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Edify Course application build started"
            channel: "devops-2510-13"
  build:
    needs: slack-notification
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4.2.2
      - name: build docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/edify-app:latest .
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to docker hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/edify-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: pull the docker image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/edify-app:latest
      - name: Run container
        run: docker container run -dt --name edify -p 80:80 ${{ vars.DOCKER_USERNAME }}/edify-app:latest
      - name: list the container
        run: docker container ls -a
  feedback:
    needs: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: send notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Edify Course application Deployed successfully go and check it in browser"
            channel: "devops-2510-13"
