name: ci-cd pipeline
on: 
  - workflow_dispatch
jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps: 
      - name: send notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Edify Course application build started"
            channel: "devops-2510-13"
