name: Version
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: vars
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t myapp:${{ env.VERSION }} .
      - name: list images
        run: docker image ls
